version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: foodgram-db
    image: postgres:13.10
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-backend
    build: ./backend/
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    container_name: foodgram-front
    build: ./frontend/
    env_file:
      - .env
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static/
  
  nginx:
    container_name: foodgram-proxy
    build: ./infra/
    env_file:
      - .env
    ports:
      - 80:80
    volumes:
      - static:/staticfiles/
      - media:/app/media
    depends_on:
      - backend
