version: '3.3'

volumes:
  pg_data:
  static:
  media:
services:
  db:
    image: postgres:13.10
    container_name: foodgram-db
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: mikva/foodgram_backend
    container_name: foodgram-backend
    env_file:
      - .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    image: mikva/foodgram_frontend
    container_name: foodgram-front
    env_file:
      - .env
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static/

  nginx:
    container_name: foodgram-proxy
    image: mikva/foodgram_proxy
    env_file:
      - .env
    ports:
      - 8080:80
    volumes:
      - static:/staticfiles/
      - media:/app/media
    depends_on:
      - backend
