# Generated by Django 3.2.16 on 2025-05-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20250502_0027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'default_related_name': 'ingredient', 'ordering': ('name',), 'verbose_name': 'продукт', 'verbose_name_plural': 'Список продуктов'},
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='unique_in_ingredients'),
        ),
    ]
