# Generated by Django 3.2.16 on 2025-05-12 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_remove_recipe_is_favorited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_in_shopping_cart',
        ),
    ]
